name = "tiny-analytics"
main = "index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB" # Dit moet hetzelfde zijn als 'env.DB' in je code
database_name = "analytics_db"
database_id = "7b140f8b-a6ac-42bd-b2da-ab7390b2e899"
ADMIN_PASSWORD = "demo"
